CREATE TABLE IF NOT EXISTS players (
    personId        INTEGER PRIMARY KEY,
    firstName       TEXT,
    lastName        TEXT,
    birthdate       TEXT,
    country         TEXT,
    height          REAL,
    bodyWeight      REAL,
    guard           TEXT,
    forward         TEXT,
    center          TEXT,
    draftYear       INTEGER,
    draftRound      INTEGER,
    draftNumber     INTEGER
);

CREATE TABLE IF NOT EXISTS team_histories (
    teamId              INTEGER,
    teamCity            TEXT,
    teamName            TEXT,
    teamAbbrev          TEXT,
    seasonFounded       INTEGER,
    seasonActiveTill    INTEGER,
    league              TEXT,
    PRIMARY KEY (teamId, seasonFounded)
);

CREATE TABLE IF NOT EXISTS games (
    gameId              INTEGER PRIMARY KEY,
    gameDateTimeEst     TEXT,
    hometeamCity        TEXT,
    hometeamName        TEXT,
    hometeamId          INTEGER,
    awayteamCity        TEXT,
    awayteamName        TEXT,
    awayteamId          INTEGER,
    homeScore           INTEGER,
    awayScore           INTEGER,
    winner              INTEGER,
    gameType            TEXT,
    attendance          REAL
);

CREATE TABLE IF NOT EXISTS player_statistics (
    personId                    INTEGER,
    gameId                      INTEGER,
    gameDateTimeEst             TEXT,
    playerteamCity              TEXT,
    playerteamName              TEXT,
    opponentteamCity            TEXT,
    opponentteamName            TEXT,
    win                         INTEGER,
    home                        INTEGER,
    numMinutes                  REAL,
    points                      REAL,
    assists                     REAL,
    blocks                      REAL,
    steals                      REAL,
    fieldGoalsAttempted         REAL,
    fieldGoalsMade              REAL,
    fieldGoalsPercentage        REAL,
    threePointersAttempted      REAL,
    threePointersMade           REAL,
    threePointersPercentage     REAL,
    freeThrowsAttempted         REAL,
    freeThrowsMade              REAL,
    freeThrowsPercentage        REAL,
    reboundsDefensive           REAL,
    reboundsOffensive           REAL,
    reboundsTotal               REAL,
    foulsPersonal               REAL,
    turnovers                   REAL,
    plusMinusPoints             REAL,
    PRIMARY KEY (personId, gameId),
    FOREIGN KEY (personId) REFERENCES players(personId),
    FOREIGN KEY (gameId)   REFERENCES games(gameId)
);

CREATE TABLE IF NOT EXISTS team_statistics (
    gameId                      INTEGER,
    teamId                      INTEGER,
    gameDateTimeEst             TEXT,
    teamCity                    TEXT,
    teamName                    TEXT,
    opponentTeamCity            TEXT,
    opponentTeamName            TEXT,
    opponentTeamId              INTEGER,
    home                        INTEGER,
    win                         INTEGER,
    teamScore                   INTEGER,
    opponentScore               INTEGER,
    assists                     REAL,
    blocks                      REAL,
    steals                      REAL,
    fieldGoalsAttempted         REAL,
    fieldGoalsMade              REAL,
    fieldGoalsPercentage        REAL,
    threePointersAttempted      REAL,
    threePointersMade           REAL,
    threePointersPercentage     REAL,
    freeThrowsAttempted         REAL,
    freeThrowsMade              REAL,
    freeThrowsPercentage        REAL,
    reboundsTotal               REAL,
    foulsPersonal               REAL,
    turnovers                   REAL,
    plusMinusPoints             REAL,
    pointsInThePaint            REAL,
    pointsFastBreak             REAL,
    pointsFromTurnovers         REAL,
    seasonWins                  REAL,
    seasonLosses                REAL,
    PRIMARY KEY (gameId, teamId),
    FOREIGN KEY (gameId) REFERENCES games(gameId)
);